name: ci-golang-workflow #nome do workflow
on:
  pull_request:  # define quando o processo de CI vai rodar
  push: 
    branches:
      - master
jobs:
  check-application: # nome do job
    runs-on: ubuntu-latest # onde o job vai rodar
    strategy:
      matrix:
        go: ['1.14', '1.15']
    steps: # quais são os passos que vão ser exeutados quando o processo iniciar  
      - uses: actions/checkout@v2 # pega os dados que acabaram de subir e baixa para a máquina do "runs-on"
      - uses: actions/setup-go@v2 # faz o setup do go na máquina
        with:
          go-version: ${{ matrix.go }}
      - run: go test
      - run: go run math.go 
      


# uses: para rodar actions
# run: para rodar comandos